Models/ShirtListModel.cs
using System.Collections.Generic;
using SUShirts.Business.Dto;
using SUShirts.Data.Enums;

namespace SUShirts.Models
{
    public class ShirtListModel
    {
        public List<ShirtDto> Shirts { get; set; }
        public SexVariant Sex { get; set; }
    }
}

Pages/Admin/ReservationDetail.cshtml.cs
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SUShirts.Business.Dto;
using SUShirts.Business.Facades;

namespace SUShirts.Pages.Admin
{
    public class ReservationDetail : PageModel
    {
        public class InternalInfoModel
        {
            public string Note { get; set; }
            public string AssignedTo { get; set; }

            public InternalInfoModel()
            {
            }

            public InternalInfoModel(ReservationDto reservationDto)
            {
                this.Note = reservationDto.InternalNote;
                this.AssignedTo = reservationDto.AssignedTo;
            }
        }

        private readonly ReservationsFacade _facade;
        public ReservationDto Reservation { get; set; }

        [BindProperty(SupportsGet = true, Name = "id")]
        public int Id { get; set; }

        [TempData] public string ErrorMessage { get; set; }

        [BindProperty] public InternalInfoModel InternalInfo { get; set; }

        public ReservationDetail(ReservationsFacade facade)
        {
            _facade = facade;
        }

        public async Task<IActionResult> OnGet()
        {
            var dto = await _facade.GetDetails(this.Id);
            if (dto is null)
            {
                return this.NotFound();
            }

            this.Reservation = dto;
            this.InternalInfo = new InternalInfoModel(dto);

            return this.Page();
        }

        public async Task<IActionResult> OnPostSetInternalInfo()
        {
            var result = await _facade.SetInternalInfo(this.Id, this.InternalInfo.AssignedTo, this.InternalInfo.Note);
            if (!result)
            {
                this.ErrorMessage = "Při ukládání změny se vyskytla chyba. Zkus to znovu.";
            }

            return this.RedirectToPage();
        }

        public async Task<IActionResult> OnGetAddItem(int variantId)
        {
            var result = await _facade.AddItem(this.Id, variantId);
            if (!result)
            {
                this.ErrorMessage = "Při ukládání změny se vyskytla chyba. Zkus to znovu.";
            }

            return this.RedirectToPage();
        }

        public async Task<IActionResult> OnGetRemoveItem(int variantId)
        {
            var result = await _facade.RemoveItem(this.Id, variantId);
            if (!result)
            {
                this.ErrorMessage = "Při ukládání změny se vyskytla chyba. Zkus to znovu.";
            }

            return this.RedirectToPage();
        }

        public async Task<IActionResult> OnGetFinish()
        {
            var result = await _facade.MarkHandled(this.Id, this.UserIdentifier);
            if (!result)
            {
                this.ErrorMessage = "Při ukládání se vyskytla chyba. Zkus to znovu.";
            }

            return this.RedirectToPage();
        }

        public async Task<IActionResult> OnGetCancel()
        {
            var result = await _facade.Cancel(this.Id, this.UserIdentifier);
            if (!result)
            {
                this.ErrorMessage = "Při ukládání se vyskytla chyba. Zkus to znovu.";
            }

            return this.RedirectToPage();
        }

        private string UserIdentifier => this.User.FindFirstValue(ClaimTypes.Name)
                                         ?? this.User.FindFirstValue(ClaimTypes.Email);
    }
}

Pages/Admin/Reservations.cshtml.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SUShirts.Business.Dto;
using SUShirts.Business.Facades;
using SUShirts.Data.Extensions;

namespace SUShirts.Pages.Admin
{
    public class Reservations : PageModel
    {
        private readonly ReservationsFacade _facade;

        public List<ReservationDto> PendingReservations { get; set; }
        public List<ReservationDto> FinishedReservations { get; set; }

        public Reservations(ReservationsFacade facade)
        {
            _facade = facade;
        }

        public async Task OnGet()
        {
            var dtos = await _facade.GetAll();
            this.PendingReservations = dtos.FindAll(r => !r.State.IsClosed());
            this.FinishedReservations = dtos.FindAll(r => r.State.IsClosed());
        }
    }
}

Pages/Index.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SUShirts.Business.Facades;
using SUShirts.Data.Enums;
using SUShirts.Models;

namespace SUShirts.Pages
{
    public class Index : PageModel
    {
        private readonly ShopFacade _facade;

        public ShirtListModel ManShirts { get; set; }
        public ShirtListModel WomanShirts { get; set; }

        public Index(ShopFacade facade)
        {
            _facade = facade;
        }

        public async Task<IActionResult> OnGet()
        {
            this.ViewData["ShowCart"] = true;
            
            var (men, women) = await _facade.GetOffers();

            this.ManShirts = new ShirtListModel() {Shirts = men, Sex = SexVariant.Man};
            this.WomanShirts = new ShirtListModel() {Shirts = women, Sex = SexVariant.Woman};

            return this.Page();
        }
    }
}

Pages/MakeReservation.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SUShirts.Business.Dto;
using SUShirts.Business.Facades;
using SUShirts.Business.Models;

namespace SUShirts.Pages
{
    public class MakeReservation : PageModel
    {
        private readonly ShopFacade _facade;

        public List<ShirtVariantRequestDto> Items { get; set; }

        [BindProperty] public ReservationModel Reservation { get; set; }

        public MakeReservation(ShopFacade facade)
        {
            _facade = facade;
        }

        public async Task<IActionResult> OnGet()
        {
            if (!this.Request.Cookies.TryGetValue("cart", out var cartCookie))
            {
                return this.RedirectToPage("Index");
            }

            var items = await _facade.GetCartItems(cartCookie);
            if (items is null or {Count: 0})
            {
                return this.RedirectToPage("Index");
            }

            this.Items = items;
            return this.Page();
        }

        public async Task<IActionResult> OnPost()
        {
            if (!this.Request.Cookies.TryGetValue("cart", out var cartCookie))
            {
                return this.RedirectToPage("Index");
            }

            var items = await _facade.GetCartItems(cartCookie);
            if (items is null or {Count: 0})
            {
                return this.RedirectToPage("Index");
            }

            if (!this.ModelState.IsValid)
            {
                this.Items = items;
                return this.Page();
            }

            var result = await _facade.MakeReservation(this.Reservation, cartCookie);
            string resultCode;

            if (result)
            {
                if (items.Any(i => !i.WillBeRequested))
                {
                    resultCode = ReservationResult.ResultVariant.MissingItems.ToString();
                }
                else
                {
                    resultCode = ReservationResult.ResultVariant.Ok.ToString();
                }

                this.Response.Cookies.Append("cart", "", new CookieOptions() {Expires = DateTimeOffset.MinValue});
            }
            else
            {
                resultCode = ReservationResult.ResultVariant.Error.ToString();
            }

            return this.RedirectToPage("ReservationResult", new {state = resultCode});
        }
    }
}

Pages/ReservationResult.cshtml.cs
using System;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SUShirts.Pages
{
    public class ReservationResult : PageModel
    {
        public enum ResultVariant
        {
            Ok,
            Error,
            MissingItems,
            BadRequest
        }

        public ResultVariant Result { get; set; }

        public void OnGet(string state)
        {
            try
            {
                this.Result = Enum.Parse<ResultVariant>(state, true);
            }
            catch
            {
                this.Result = ResultVariant.BadRequest;
            }
        }
    }
}

Pages/Admin/Partials/_ReservationListPartial.cshtml
@using SUShirts.Data.Extensions
@model List<SUShirts.Business.Dto.ReservationDto>

@if (Model is null or {Count:0})
{
    <h4>Nic tady není.</h4>
}
else
{
    <div class="table-responsive">
        <table class="table">
            <thead>
            <tr>
                <th scope="col">Jméno</th>
                <th scope="col">Vytvořeno</th>
                <th scope="col">Celkem kusů</th>
                <th scope="col">Cena celkem</th>
                @if (Model[0].State.IsClosed())
                {
                    <th scope="col">
                        Vyřízeno
                    </th>
                }
                else
                {
                    <th scope="col">
                        Vyřizuje
                    </th>
                }
                <th scope="col"></th>
            </tr>
            </thead>
            <tbody>
            @foreach (var item in Model.OrderByDescending(r => r.MadeOn))
            {
                <tr>
                    <th>@item.Name</th>
                    <td>@item.MadeOn.ToString("dd. MM. yyyy HH:mm")</td>
                    <td>@item.Items.Select(i => i.Count).Sum()</td>
                    <td>@item.Items.Select(i => i.Price * i.Count).Sum() Kč</td>
                    @if (item.State.IsClosed())
                    {
                        <td>@item.HandledOn!.Value.ToString("dd. MM. yyyy HH:mm") (@item.HandledBy)</td>
                    }
                    else
                    {
                        <td class="@(item.AssignedTo is null ? "text-danger" : "")">@(item.AssignedTo ?? "zatím nikdo")</td>
                    }
                    <td>
                        <a asp-page="ReservationDetail" asp-route-Id="@item.Id" class="btn btn-outline-primary">Detail</a>
                    </td>
                </tr>
            }
            </tbody>
        </table>
    </div>
}

Pages/Admin/ReservationDetail.cshtml
@page "/Admin/Reservations/{id:int}"
@using SUShirts.Data.Enums
@using SUShirts.Data.Extensions
@model SUShirts.Pages.Admin.ReservationDetail

<h2>
    Rezervace #@Model.Reservation.Id –
    <span class="@(Model.Reservation.State switch { 
                     ReservationState.New => "text-danger",
                     ReservationState.Assigned => "text-warning",
                     ReservationState.Finished => "text-success",
                     ReservationState.Cancelled => "text-success",
                     _ => throw new ArgumentOutOfRangeException()})">
        @(Model.Reservation.State switch {
            ReservationState.New => "nevyřízená",
            ReservationState.Assigned => "přiřazená",
            ReservationState.Finished => "vyřízená",
            ReservationState.Cancelled => "zrušená",
            _ => throw new ArgumentOutOfRangeException()})
    </span>
</h2>

@if (Model.ErrorMessage is not null)
{
    <div class="alert alert-danger" role="alert">
        @Model.ErrorMessage
    </div>
}

<p>
    Jméno: @Model.Reservation.Name<br>
    E-mail: <a href="mailto:@Model.Reservation.Email">@Model.Reservation.Email</a><br>
    Telefon/Discord: @(Model.Reservation.PhoneOrDiscordTag ?? "neuveden")<br>
</p>

@if (!string.IsNullOrEmpty(Model.Reservation.Note))
{
    <h5>Poznámka rezervujícího</h5>
    <p>
        @Html.Raw(Model.Reservation.Note.Replace("\n", "<br>"))
    </p>
}

<table class="table mb-4">
    <thead>
    <tr>
        <th scope="col">Název</th>
        <th scope="col">Velikost</th>
        <th scope="col">Střih</th>
        <th scope="col">Cena</th>
        <th scope="col">
            @if (Model.Reservation.State.IsClosed())
            {
                @:Vydaných kusů 
            }
            else
            {
                @:Požadovaných kusů 
            }
        </th>
        <th scope="col">Kusů na skladě</th>
        <th scope="col">Kusů k dispozici</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model.Reservation.Items.OrderBy(ri => ri.ShirtSex).ThenBy(ri => ri.ShirtName).ThenBy(ri => ri.ShirtSize))
    {
        <tr>
            <th scope="row">@item.ShirtName</th>
            <td>@item.ShirtSize.ToString()</td>
            <td>@(item.ShirtSex switch { SexVariant.Man => "pánský", SexVariant.Woman => "dámský", SexVariant.Unisex => "uni", _ => "?"})</td>
            <td>@item.Price Kč</td>
            <td>
                @item.Count&nbsp;
                @if (!Model.Reservation.State.IsClosed())
                {
                    if (item.Count > 0)
                    {
                        <a asp-page-handler="RemoveItem" asp-route-variantId="@item.ShirtVariantId" class="btn btn-outline-secondary">
                            <i class="fa fa-minus"></i>
                        </a>
                    }

                    if (item.LeftForReserving > 0)
                    {
                        <a asp-page-handler="AddItem" asp-route-variantId="@item.ShirtVariantId" class="btn btn-outline-secondary">
                            <i class="fa fa-plus"></i>
                        </a>
                    }
                }
            </td>
            <td>@item.InStock</td>
            <td>@item.LeftForReserving</td>
        </tr>
    }
    </tbody>
</table>

<h5>Interní informace</h5>
@if (Model.Reservation.State.IsClosed())
{
    <p>
        Vyřizoval (přiřazený člověk): @Model.InternalInfo.AssignedTo<br>
        Vyřídil (potvrdil/zrušil): @Model.Reservation.HandledBy (@Model.Reservation.HandledOn!.Value.ToString("dd. MM. yyyy HH:mm"))
    </p>

    if (!string.IsNullOrEmpty(Model.InternalInfo.Note))
    {
        <h6>Poznámka</h6>
        <p>
            @Html.Raw(Model.InternalInfo.Note.Replace("\n", "<br>"))
        </p>
    }
}
else
{
    <form method="post" asp-page-handler="SetInternalInfo">
        <div class="mb-3">
            <label asp-for="InternalInfo.AssignedTo" class="form-label">Vyřizuje</label>
            <input type="text" class="form-control" asp-for="InternalInfo.AssignedTo">
            <span asp-validation-for="InternalInfo.AssignedTo" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="InternalInfo.Note" class="form-label">Interní poznámka</label>
            <textarea class="form-control" style="height: 6em;" asp-for="InternalInfo.Note" placeholder="předám mu to příští týden…"></textarea>
            <span asp-validation-for="Reservation.Note" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-outline-secondary mb-4">Uložit</button>
    </form>
}

@if (!Model.Reservation.State.IsClosed())
{
    <a asp-page-handler="Finish" class="btn btn-primary">Označit jako vyřízenou</a>
    <a asp-page-handler="Cancel" class="btn btn-outline-danger">Zrušit</a>

    <div class="form-text">
        Označením za vyřízenou stvrzuji, že jsem přebral peníze a vydal jsem trička (případně že peníze došly na účet a domluvil jsem se na jeho předání).
    </div>
}

<a asp-page="Reservations" class="d-block mt-2">Zpět na rezervace</a>

Pages/Admin/Reservations.cshtml
@page
@model SUShirts.Pages.Admin.Reservations

<h2>Rezervace</h2>

<div class="accordion mb-4">
    <div class="accordion-item">
        <h2 class="accordion-header">
            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#pendingReservations">
                Nevyřízené rezervace
            </button>
        </h2>
        <div id="pendingReservations" class="accordion-collapse collapse show">
            <div class="accordion-body">
                <partial name="Partials/_ReservationListPartial" model="@Model.PendingReservations"/>
            </div>
        </div>
    </div>
    <div class="accordion-item">
        <h2 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#finishedReservations">
                Vyřízené rezervace
            </button>
        </h2>
        <div id="finishedReservations" class="accordion-collapse collapse">
            <div class="accordion-body">
                <partial name="Partials/_ReservationListPartial" model="@Model.FinishedReservations"/>
            </div>
        </div>
    </div>
</div>


<h2>Sklad</h2>
<p>TODO :)</p>

Pages/Index.cshtml
@page
@model SUShirts.Pages.Index

<h2 id="damska">Dámská</h2>
<partial name="Partials/_ShirtListPartial" model="Model.WomanShirts"/>

<h2 id="panska">Pánská</h2>
<partial name="Partials/_ShirtListPartial" model="Model.ManShirts"/>

<div class="col-md-12 text-center mb-4">
    <button class="btn btn-outline-primary cart-btn">Přejít do košíku</button>
</div>

@section Scripts
{
    <script>
        const makeReservationUrl = "@Url.Page("MakeReservation")";
    </script>

    <script src="~/js/shop.js"></script>
}

Pages/MakeReservation.cshtml
@page
@model SUShirts.Pages.MakeReservation

<h2>Zarezervovat trička</h2>

<div class="table-responsive">
    <table class="table mb-4">
        <thead>
        <tr>
            <th scope="col">Název</th>
            <th scope="col">Velikost</th>
            <th scope="col">Cena</th>
            <th scope="col">Požadovaných kusů</th>
            <th scope="col">Kusů skladem</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var item in Model.Items)
        {
            <tr class="@(item.WillBeRequested ? "" : "table-danger")">
                <th scope="row">@item.ShirtName</th>
                <td>@item.Size.ToString()</td>
                <td>@item.Price Kč</td>
                <td>
                    @item.RequestedCount
                    @if (!item.WillBeRequested)
                    {
                        <i class="fa fa-warning" title="Této položky je skladem menší množství kusů, nebude zahrnuta do rezervace!" data-bs-toggle="tooltip"></i>
                    }
                </td>
                <td>@item.ItemsLeft</td>
            </tr>
        }
        </tbody>
    </table>
</div>

<h4>Rezervační formulář</h4>
<div class="col-md-6 mt-2">
    <form method="post">
        <div class="mb-3">
            <label asp-for="Reservation.Email" class="form-label">E-mail</label>
            <input type="email" class="form-control" asp-for="Reservation.Email" autocomplete="email">
            <span asp-validation-for="Reservation.Email" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Reservation.Name" class="form-label">Jméno</label>
            <input type="text" class="form-control" asp-for="Reservation.Name" autocomplete="name">
            <span asp-validation-for="Reservation.Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Reservation.PhoneOrDiscordTag" class="form-label">Telefon nebo Discord tag</label>
            <input type="text" class="form-control" asp-for="Reservation.PhoneOrDiscordTag" autocomplete="tel">
            <span asp-validation-for="Reservation.PhoneOrDiscordTag" class="text-danger"></span>
        </div>
        <div class="mb-3 form-check">
            <input type="checkbox" class="form-check-input" asp-for="Reservation.IsClubMember">
            <label class="form-check-label" asp-for="Reservation.IsClubMember">Jsem zaregistrovaný v Kachně</label>
            <div class="form-text">(jsem sympatizujícím nebo jiným členem SU)</div>
        </div>
        <div class="mb-3">
            <label asp-for="Reservation.Note" class="form-label">Poznámka</label>
            <textarea class="form-control" asp-for="Reservation.Note" placeholder="chci předat tričko na PPV, můžu si tričko vyzvednout v úterý a v pátek na FITu…"></textarea>
            <span asp-validation-for="Reservation.Note" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary">Odeslat rezervaci</button>
        <div class="form-text">
            Rezervace je nezávazná. Trička si můžeš při předání vyzkoušet a třeba si vzít jinou velikost. Po odeslání tě bude kontaktovat člen SU, se kterým se domluvíš na platbě a předání.
        </div>
    </form>
</div>

@section Scripts
{
    <script>
        const tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
        const tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
          return new bootstrap.Tooltip(tooltipTriggerEl)
        })
    </script>
    <script src="~/js/jquery.validate.min.js" asp-append-version="true"></script>
    <script src="~/js/jquery.validate.unobtrusive.min.js" asp-append-version="true"></script>
}

Pages/Partials/_ShirtListPartial.cshtml
@using SUShirts.Data.Enums
@model SUShirts.Models.ShirtListModel

<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-xxl-4 g-3 mb-4">
    @foreach (var dto in Model.Shirts)
    {
        <div class="col">
            <div class="card shirt-item" data-sid="@dto.Id">
                <img src="@Url.Content($"~{dto.ImageUrl}")" alt="Fotka trička" class="card-img-top"/>
                <div class="card-body">
                    <h5 class="card-title">@dto.Name</h5>
                    <div class="card-text">
                        <div class="row align-items-start mt-2">
                            <div class="col-auto col-form-label">
                                <label class="form-label">Velikost:</label>
                            </div>
                            <div class="col">
                                <select class="form-select variant-select" data-sid="@dto.Id">
                                    @foreach (var variant in dto.Variants)
                                    {
                                        <option value="@variant.Id" data-price="@variant.Price" data-left="@variant.ItemsLeft">
                                            @variant.Size.ToString()
                                            @if (variant.Sex == SexVariant.Unisex)
                                            {
                                                @:(unisex)
                                            }
                                        </option>
                                    }
                                </select>
                            </div>
                        </div>

                        <hr class="mt-2">
                        <div class="row align-items-baseline">
                            <div class="col-auto">
                                <h5 class="price-label">@dto.Variants[0].Price Kč</h5>
                            </div>
                            <div class="col">
                                skladem <span class="left-label">@dto.Variants[0].ItemsLeft</span> ks
                            </div>
                            <div class="col-auto">
                                <button class="btn btn-primary disabled minus-btn">
                                    <i class="fa fa-minus"></i>
                                </button>
                                <span class="items-counter">0</span>
                                <button class="btn btn-primary plus-btn">
                                    <i class="fa fa-plus"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

Pages/ReservationResult.cshtml
@page "{state?}"
@model SUShirts.Pages.ReservationResult

@switch (Model.Result)
{
    case ReservationResult.ResultVariant.Ok:
        <h2>Zarezervováno</h2>
        <p>
            Tvá trička byla úspěšně zarezervována. Nyní prosím počkej, kontaktuje tě někdo z SU a domluvíte se na předání.
        </p>
        break;
    case ReservationResult.ResultVariant.Error:
        <h2>Chyba</h2>
        <pre>
IDS/2020L: 49 b -> 49 b, zap 2021-05-13, 4F @DateTime.Today.ToString("yyyy-MM-dd")</pre>
        <p>
            Při rezervování nastala chyba. Zkus to znovu.
        </p>
        break;
    case ReservationResult.ResultVariant.MissingItems:
        <h2>Zarezervováno</h2>
        <p>
            Tvá trička byla úspěšně zarezervována.
            Pozor, některé předměty z rezervace ti někdo stihl vyfouknout.<br>
            Nyní prosím počkej, kontaktuje tě někdo z SU a domluvíte se na předání.
        </p>
        break;
    case ReservationResult.ResultVariant.BadRequest:
        <h2>Ani to nezkoušej</h2>
        break;
    default:
        throw new ArgumentOutOfRangeException();
}

@section Scripts
{
    @if (Model.Result is ReservationResult.ResultVariant.Ok or ReservationResult.ResultVariant.MissingItems)
    {
        <script>
            localStorage.clear();
        </script>
    }
}

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>

<html lang="cs">
<head>
    <title>SU trička</title>

    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="icon" type="image/png" href="~/favicon-32x32.png"/>

    <link href="~/css/bootstrap.css" asp-append-version="true" rel="stylesheet"/>
    <link href="~/css/font-awesome.css" asp-append-version="true" rel="stylesheet"/>
    @await RenderSectionAsync("Styles", false)
</head>
<body>

<div class="container">
    <header class="navbar d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
        <a href="~/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
            <img src="~/images/logo_horizontalni.svg" height="64" alt="logo"/>
        </a>

        <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
            <li>
                <a href="~/#damska" class="nav-link">Dámská trička</a>
            </li>
            <li>
                <a href="~/#panska" class="nav-link">Pánská trička</a>
            </li>
            <li>
        </ul>

        @if (true.Equals(ViewData["ShowCart"]))
        {
            <div class="col-md-3 text-end">
                <button type="button" class="btn btn-primary text-white cart-btn">
                    <i class="fa fa-shopping-cart me-2"></i><span class="cart-text">0</span>
                </button>
            </div>
        }
    </header>
</div>

<div class="container">
    @RenderBody()
</div>

<script src="~/js/popper.min.js" asp-append-version="true"></script>
<script src="~/js/bootstrap.min.js" asp-append-version="true"></script>
<script src="~/js/jquery.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", false)
</body>
</html>